name: Build and Push Docker Image

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Build type'
        required: true
        default: 'all'
        type: choice
        options:
        - all
        - cpu-only
        - gpu-only
      push_images:
        description: 'Push images to registry'
        required: true
        default: true
        type: boolean
      version_tag:
        description: 'Version tag (optional)'
        required: false
        default: ''
        type: string

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}/${{ github.event.repository.name }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        if: github.event.inputs.push_images == 'true'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value=${{ github.event.inputs.version_tag }},enable=${{ github.event.inputs.version_tag != '' }}

      - name: Extract GPU metadata
        id: gpu-meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest-gpu,enable={{is_default_branch}}
            type=raw,value=${{ github.event.inputs.version_tag }}-gpu,enable=${{ github.event.inputs.version_tag != '' }}

      - name: Build and push CPU Docker image
        if: github.event.inputs.build_type == 'all' || github.event.inputs.build_type == 'cpu-only'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event.inputs.push_images == 'true' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false
          sbom: false

      - name: Build and push GPU Docker image
        if: github.event.inputs.build_type == 'all' || github.event.inputs.build_type == 'gpu-only'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.gpu
          platforms: linux/amd64
          push: ${{ github.event.inputs.push_images == 'true' }}
          tags: ${{ steps.gpu-meta.outputs.tags }}
          labels: ${{ steps.gpu-meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false
          sbom: false

  test-image:
    runs-on: ubuntu-latest
    needs: build-and-push
    if: github.event.inputs.push_images == 'true' && (github.event.inputs.build_type == 'all' || github.event.inputs.build_type == 'cpu-only')
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}

      - name: Pull and test image
        run: |
          # 拉取镜像
          docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          
          # 启动容器进行测试
          docker run -d --name mixtex-test -p 8000:8000 \
            -e MODEL_PATH=/app/model \
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          
          # 等待容器启动
          sleep 30
          
          # 健康检查
          curl -f http://localhost:8000/health || exit 1
          
          # 清理
          docker stop mixtex-test
          docker rm mixtex-test

  security-scan:
    runs-on: ubuntu-latest
    needs: build-and-push
    if: github.event.inputs.push_images == 'true' && (github.event.inputs.build_type == 'all' || github.event.inputs.build_type == 'cpu-only')
    
    steps:
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'
